services:
  nmsoft-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nmsoft-site
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - traefik

    labels:
      - traefik.enable=true
      - traefik.http.routers.nmsoft.co.rule=Host(`nmsoft.co`)
      - traefik.http.routers.nmsoft.co.entrypoints=websecure
      - traefik.http.routers.nmsoft.co.tls=true
      - traefik.http.routers.nmsoft.co.tls.certresolver=myresolver
      - traefik.docker.network=traefik
      - traefik.http.services.nmsoft.co.loadbalancer.server.port=3000

networks:
  traefik:
    external: true
