entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /dynamic.yml

certificatesResolvers:
  myresolver:
    acme:
      email: redem.mnd@gmail.com      
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web